# Generated by Django 4.2.7 on 2023-11-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Usuarios',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_login',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuario',
            new_name='nick',
        ),
    ]
