# Generated by Django 4.2.7 on 2023-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_rename_login_usuarios_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
