# Generated by Django 5.0.1 on 2024-02-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='id_post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
