# Generated by Django 3.2.23 on 2024-01-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20240121_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
