# Generated by Django 5.0.1 on 2024-01-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
        ('users', '0004_remove_user_username'),
    ]

    operations = [
    ]
