# Generated by Django 5.0.1 on 2024-02-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_comment_posted_at_like_like_at_alter_post_posted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_at',
            new_name='liked_at',
        ),
    ]
